<a href="https://colab.research.google.com/github/Javcm/Intro-a-Deep-Learning-UNAM-FC/blob/main/Tutorial_Numpy_2022_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src = "https://drive.google.com/uc?id=17atj9OubRtxp1m0gVTwAGORykjvdxWA0" align = "center" >

<font color = 'BlackCyan' size = 8>
Tutorial Numpy

<font size=4>
En este Notebook se aborda el uso de la paquetería Numpy y su aplicación en diversas áreas.

<font size = 5, color = "blue">
1.- ¿Por qué Numpy?

<font size=4>
Numpy es una biblioteca que se ha vuelto esencial para el cómputo científico al utilizar el lenguaje de programación Python.
Destaca como una de las bibliotecas más recurrentes y útilies debido a que permite realizar operaciones con mayor sencillez y eficiencia.

## <font size=4> Cualquier cosa que quieras saber de esta biblioteca en el futuro lo puedes encontrar [aquí](https://numpy.org/doc/stable/)


<font size = 5, color = "blue">
2.- Ventajas de utilizar Numpy

<font size = 4>

Comparemos la biblioteca **math** y **numpy** al definir la función Sigmoide, la cual es una función muy utilizada en Deep Learning. En particular observemos la forma en que operan **math.exp()** y **np.exp()**:

<font size = 4>
Recordando que: 
$sigmoid(x) = \frac{1}{1+e^{-x}}$ 

<img src = "https://drive.google.com/uc?id=1NdvUhSr_AGYmQ1XByZUcfq87d36wvKi_" align = "center" >

In [ ]:
#Definimos la función utilizando la biblioteca math:

import math

def sigmoide_math(x):
    '''
    Input: elemento del tipo int o float
    output: elemento del tipo int o float
    '''
    return 1/(1 + math.exp(-x))

<font size = 4>

Las entradas de la función sigmoide suelen ser vectores, en este caso probaremos con enteros, flotantes y vectores:

In [ ]:
#Calculamos el valor de sigmoide para x = 1 como entero y flotante:

x = 1 #int(1)
y = 1. #float(1)

print("x es del tipo {} y sigmoide(x) tiene el valor {:.5f}\n y es del tipo {} y sigmoide(y) tiene el valor {:.5f}."\
      .format( type(x), sigmoide_math(x), type(y), sigmoide_math(y) ) )


#print("database es una {} con {} elements and shape {}.".format(type(database), len(database), database.shape))

x es del tipo <class 'int'> y sigmoide(x) tiene el valor 0.73106
 y es del tipo <class 'float'> y sigmoide(y) tiene el valor 0.73106.


<font size = 4>
    
Observamos que no hay diferencia.

<font size = 4>
    
Ahora bien, si intentamos calcular el valor de **sigmoide_math()** de X = [1,2,3], obtenemos:

In [ ]:
X = [1,2,3]

sigmoide_math(X)

TypeError: ignored

<font size = 4>

Este error se debe a que **math** funciona con variables del tipo entero y flotante.

In [ ]:
#Importamos Numpy

import numpy as np  #pip install numpy
                    #conda install numpy

<font size = 4>

Probemos utilizando **np.exp()** para los tres tipos de variable: entero, flotante, vector(arreglo):

In [ ]:
np.exp?

In [ ]:
#Definimos la función sigmoid utilizando Numpy:

def sigmoid_np(x):
    """
    Input: Vector X del tipo arreglo de numpy
    Output: Arreglo de numpy
    """
    return 1/(1 + np.exp(-x))

In [ ]:
sigmoid_np(X) #X = [1,2,3]

TypeError: ignored

In [ ]:
#Numpy no puede calcular la exponencial de una lista, debemos convertir esa lista
#en un arreglo de Numpy.

X = np.array([1,2,3])

print(X, type(X))

[1 2 3] <class 'numpy.ndarray'>


In [ ]:
#Evaluamos con x, y, X:

print("'x' es del tipo {} y sigmoide(x) tiene el valor {:.5f}. \n\n 'y' es del tipo {} y sigmoide(y) tiene el valor {:.5f}.\
 \n\n 'X' es del tipo {} y sigmoid de X tiene el valor de {}."\
      .format(type(x), sigmoid_np(x),type(y), sigmoid_np(y), type(X), sigmoid_np(X)))

'x' es del tipo <class 'int'> y sigmoide(x) tiene el valor 0.73106. 

 'y' es del tipo <class 'float'> y sigmoide(y) tiene el valor 0.73106. 

 'X' es del tipo <class 'numpy.ndarray'> y sigmoid de X tiene el valor de [0.73105858 0.88079708 0.95257413].


<font size = 4>

Lo que ocurre es que **Numpy** calcula la exponencial de cada una de las entradas del vector 'X' y regresa np.exp(X) como un vector de la misma forma que 'X'.
    
<font color = "red">    

$$ \text{For } x \in \mathbb{R}^n \text{,     } sigmoid(x) = sigmoid\begin{pmatrix}
    x_1  \\
    x_2  \\
    ...  \\
    x_n  \\
\end{pmatrix} = \begin{pmatrix}
    \frac{1}{1+e^{-x_1}}  \\
    \frac{1}{1+e^{-x_2}}  \\
    ...  \\
    \frac{1}{1+e^{-x_n}}  \\
\end{pmatrix}\tag{1} $$

<font size = 5, color = "blue">
3.- Gradiente de la Función Sigmoide

<font size = 4>

Como se verá más adelante, para optimizar una función de pérdida se requiere calcular el gradiente de funciones al hacer retropropagación (Gradient Descent). En este sentido, calculemos el **gradiente** de la función **sigmoide** el cual se determina mediante la ecuación (recordando que  $sigmoid(x) = \frac{1}{1+e^{-x}}$ )

 $$ sigmoid\_gradient (x) = \sigma '(x) = \sigma (x) (1 - \sigma (x)) \tag {2} $$
    
Puedes comprobar que la ecuación es correcta diferenciando respecto a la variable de la función.

In [ ]:
# EJERCICIO 

# Implementa la función sigmoid_gradient(x) 



def sigmoid_gradient(x):
    """
    Input: x, un entero, flotante o arreglo de numpy.
    output: gradiente de sigmoid(x), flotante.
    """
    # código 
    
    sig_grad = 
    
    return sig_grad

In [ ]:
#Probamos con el arreglo X definido previamente

sigmoid_gradient(X)

array([0.19661193, 0.10499359, 0.04517666])

<font size = 5, color = "blue">
4.- Array Reshape

<font size = 4>

Veamos el funcionamiento de dos atributos muy utilizados en el tratamiento de datos con Numpy: **np.shape()** y **np.reshape()**.

<font size = 4>

1.- **np.shape()** se utiliza para saber las dimensiones de un arreglo de numpy. Esto se puede interpretar como las dimensiones de una matriz.
    
2.- **np.reshape()** se utiliza para cambiar las dimensiones del arreglo (matriz) de numpy.

<font size = 4>

Estas funciones son muy frecuentes al implementar redes neuronales convolucionales. Esto ya que se suele modelar a las imágenes como un arreglo de pixeles a los cuales les corresponde un valor entre 0 y 255 para cada uno de los colores rojo, verde y azul (RGB). Formando un arreglo de 3 dimensiones ($largo$, $ancho$, $profundo$).

<font size = 4>

Este arreglo se reordena como un vector de 1 dimensión: ($largo$$*$$ancho$$*$$profundo$) al introducirlo al modelo de la red neuronal. En inglés a este vector se le denomina 'flatten'.

<img src = "https://drive.google.com/uc?id=1chF7upglVNOFlR5x7jNEt4nkSWdb5jAc" align = "center" >

<font size = 4>

Implementemos la función **np.reshape** reordenando un arreglo de la forma (3,3,2) en un arreglo de la forma (18,1):

In [ ]:
#Definimos la función Reshape:

def image2vector(image):
    """
    Input:
    imagen -- arreglo de numpy de la forma (longitud, anchura, profundidad)
    
    Returns:
    v -- vector de la forma (longitud*anchura*profundidad, 1)
    """
    
    v = image.reshape( (image.shape[0]*image.shape[1]*image.shape[2]), 1)
    
    return v

<font size=3> Puedes aprender más del atributo **np.reshape()** en el siguiente [enlace](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html).

In [ ]:
#Definimos un arreglo de prueba y comprobamos:

image = np.array([[[ 0.67826139,  0.29380381],
                   [ 0.90714982,  0.52835647],
                   [ 0.4215251 ,  0.45017551]],

                  [[ 0.92814219,  0.96677647],
                   [ 0.85304703,  0.52351845],
                   [ 0.19981397,  0.27417313]],

                  [[ 0.60659855,  0.00533165],
                   [ 0.10820313,  0.49978937],
                   [ 0.34144279,  0.94630077]] 
                  ])

image.shape

(3, 3, 2)

In [ ]:
image_flatten = image2vector(image)
image_flatten.shape

(18, 1)

In [ ]:
image_flatten

array([[0.67826139],
       [0.29380381],
       [0.90714982],
       [0.52835647],
       [0.4215251 ],
       [0.45017551],
       [0.92814219],
       [0.96677647],
       [0.85304703],
       [0.52351845],
       [0.19981397],
       [0.27417313],
       [0.60659855],
       [0.00533165],
       [0.10820313],
       [0.49978937],
       [0.34144279],
       [0.94630077]])

<font size = 5, color = "blue">
5.- Broadcast y normalización

<font size = 4>

Un proceso fundamental en algoritmos de Deep learning es la normalización de los datos con lo que se entrenará una red neuronal.
Por ejemplo, es posible normalizar una matriz o arreglo a partir de normalizar cada uno de sus renglones o filas.
Esto es, dada la matriz $$x:
\begin{bmatrix}
    0 & 3 & 4 \\
    2 & 6 & 4 \\
\end{bmatrix}\tag{1}$$ entonces $$\| x\| = \begin{bmatrix}
    5 \\
    \sqrt{56} \\
\end{bmatrix}\tag{2} $$ y        $$ x\_normalized = \frac{x}{\| x\|} = \begin{bmatrix}
    0 & \frac{3}{5} & \frac{4}{5} \\
    \frac{2}{\sqrt{56}} & \frac{6}{\sqrt{56}} & \frac{4}{\sqrt{56}} \\
\end{bmatrix}\tag{3}$$



<font size = 4>

Implementemos una función que nos permita llevar acabo la operación, haremos uso del atributo de numpy **np.linalg.norm(x)**.

In [ ]:
#Función que normaliza cada renglón de un arreglo:

def normalizeRows(x):
    """
    Input:
    x -- Un arreglo de numpy de la forma (n, m)
    
    Output:
    x -- El arreglo x con cada uno de sus renglones normalizado.
    """
    x_norm = np.linalg.norm(x, axis = 1, keepdims = True)
    
    
    # Broadcast
    x = x / x_norm

    return x

In [ ]:
#Probamos la función:

x = np.array([
    [0, 3, 4],
    [1, 6, 4]])
x.shape

(2, 3)

In [ ]:
x_normalizada = normalizeRows(x)
x_normalizada

array([[0.        , 0.6       , 0.8       ],
       [0.13736056, 0.82416338, 0.54944226]])

<font size = 4>

Observemos con detenimento la operación $x/x_{norm}$.

Cada uno de estos arreglos tiene las siguientes dimensiones.

In [ ]:
#Definimos x_norm:
x_norm = np.linalg.norm(x, axis = 1, keepdims = True)
print(x_norm)

[[5.        ]
 [7.28010989]]


In [ ]:
#Definimos x/x_norm
x_rowunit = x/x_norm
print(x_rowunit)

[[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [ ]:
x + x_norm

array([[ 5.        ,  8.        ,  9.        ],
       [ 8.28010989, 13.28010989, 11.28010989]])

In [ ]:
print("El arreglo x tiene dimensión {}, mientras que el arreglo x_norm tiene dimensión {}.\n\nPero el arreglo x/x_norm tiene dimensiones {}. Es decir las mismas que x." \
      .format(x.shape,x_norm.shape, x_rowunit.shape)) 

El arreglo x tiene dimensión (2, 3), mientras que el arreglo x_norm tiene dimensión (2, 1).

Pero el arreglo x/x_norm tiene dimensiones (2, 3). Es decir las mismas que x.


In [ ]:
#Definimos el vector x más la adición de un escalar:

x_escalar = x + 5

print("El arreglo x tiene dimensión {}, mientras que el arreglo x_escalar tiene dimensión {}".format(x.shape,x_escalar.shape)) 

El arreglo x tiene dimensión (2, 3), mientras que el arreglo x_escalar tiene dimensión (2, 3)


<font size = 4> Observemos quién es **x_escalar**

## ¿Qué pueden argumentar? 

In [ ]:
print(x.shape)

print(x)
print("\n")

print(x_escalar.shape)
print(x_escalar)

(2, 3)
[[0 3 4]
 [1 6 4]]


(2, 3)
[[ 5  8  9]
 [ 6 11  9]]


In [ ]:
x_s = np.array([5 , 5, 5])
x_ss = x_s[np.newaxis, :]
x_ss.shape

(1, 3)

In [ ]:
x + x_ss

array([[ 5,  8,  9],
       [ 6, 11,  9]])

<font size=4> Puedes entender mejor el Broadcasting [aquí](https://numpy.org/doc/stable/user/basics.broadcasting.html)

<font size = 4>

Como un ejercicio extra de broadcasting implementemos la función **Softmax**, esta se define como:
    
    
- $ \text{Sea } x \in \mathbb{R}^{1\times n} \text{,       } softmax(x) = softmax(\begin{bmatrix}
    x_1  &&
    x_2 &&
    ...  &&
    x_n  
\end{bmatrix}) = \begin{bmatrix}
     \frac{e^{x_1}}{\sum_{j}e^{x_j}}  &&
    \frac{e^{x_2}}{\sum_{j}e^{x_j}}  &&
    ...  &&
    \frac{e^{x_n}}{\sum_{j}e^{x_j}} 
\end{bmatrix} $ 

- $\text{Para un arreglo } x \in \mathbb{R}^{m \times n} \text{,  $x_{ij}$ asigna al elemento en el $i^{th}$ renglon y $j^{th}$ columna de $x$, entonces tenemos: }$  $$softmax(x) = softmax\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{m1} & x_{m2} & x_{m3} & \dots  & x_{mn}
\end{bmatrix} = \begin{bmatrix}
    \frac{e^{x_{11}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{12}}}{\sum_{j}e^{x_{1j}}} & \frac{e^{x_{13}}}{\sum_{j}e^{x_{1j}}} & \dots  & \frac{e^{x_{1n}}}{\sum_{j}e^{x_{1j}}} \\
    \frac{e^{x_{21}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{22}}}{\sum_{j}e^{x_{2j}}} & \frac{e^{x_{23}}}{\sum_{j}e^{x_{2j}}} & \dots  & \frac{e^{x_{2n}}}{\sum_{j}e^{x_{2j}}} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    \frac{e^{x_{m1}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m2}}}{\sum_{j}e^{x_{mj}}} & \frac{e^{x_{m3}}}{\sum_{j}e^{x_{mj}}} & \dots  & \frac{e^{x_{mn}}}{\sum_{j}e^{x_{mj}}}
\end{bmatrix} = \begin{pmatrix}
    softmax\text{(first row of x)}  \\
    softmax\text{(second row of x)} \\
    ...  \\
    softmax\text{(last row of x)} \\
\end{pmatrix} $$

In [ ]:
# EJERCICIO: Implementa la función softmax descrita previamente

### HINT visita el link: https://numpy.org/doc/stable/reference/generated/numpy.sum.html

#Función Softmax:

def softmax(x):
    """
    Input:
    x -- Un arreglo con dimensiones (n,m)
    
    Output:
    s -- Un arreglo igual a la función softmax de x con dimensiones (n,m)
    """
   
   
   #Broadcast
    s = 
    return s

In [ ]:
#Calculamos la función softmax de un arreglo:

x = np.array([[9, 2, 5, 0, 0], [7, 5, 0, 0 ,0]])

print("x es un arreglo de dimensiones {} y softmax(x) es un arreglo con dimensiones {}. \n\nPor su parte softmax(x) tiene los valores: \n\n{}"\
     .format(x.shape, softmax(x).shape, softmax(x)))

x es un arreglo de dimensiones (2, 5) y softmax(x) es un arreglo con dimensiones (2, 5). 

Por su parte softmax(x) tiene los valores: 

[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [ ]:
#Calculamos la función softmax de un arreglo:

x = np.array([[9, 2, 5, 0, 0], [7, 5, 0, 0 ,0]])

print("x es un arreglo de dimensiones {} y softmax(x) es un arreglo con dimensiones {}. \n\nPor su parte softmax(x) tiene los valores: \n\n{}"\
     .format(x.shape, softmax(x).shape, softmax(x)))

x es un arreglo de dimensiones (2, 5) y softmax(x) es un arreglo con dimensiones (2, 5). 

Por su parte softmax(x) tiene los valores: 

[[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


<font size = 5, color = "blue">
6.- Vectorización

<font size=4>
    
Como se ha mencionado, en deep learning se manejan conjuntos de datos muy grandes. De manera que una función no computacionalmente óptima puede convertirse en un gran cuello de botella en el algoritmo y puede dar como resultado un modelo que demore años en ejecutarse. Para asegurarse de que el código sea computacionalmente eficiente se utiliza la vectorización. 

In [ ]:
import time  #Biblioteca utilizada para contar el tiempo de ejecución.

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]



#Implementación del producto punto clásico entre vectores

tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot += x1[i]*x2[i]
toc = time.process_time()
print ("Producto punto = " + str(dot) + "\n ----- Tiempo de cálculo = " + str(1000*(toc - tic)) + "ms")


Producto punto = 278
 ----- Tiempo de cálculo = 0.11801999999860868ms


<font size=4>
    
Comparemos con las mismas operaciones utilizando la vectorización de Numpy:

In [ ]:
x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

#Producto punto entre vectores de numpy

tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("Producto punto = " + str(dot) + "\n ----- Tiempo de cálculo = " + str(1000*(toc - tic)) + "ms")

Producto punto = 278
 ----- Tiempo de cálculo = 0.07276999999916711ms


VECTORIZACIÓN ~ técnicas que perminten "quitar"  bucles explícitos en el código 